book/urls.py
from django.urls import path
from book.views import BookList, BookDetail, AuthorList, AuthorDetail, BookUploadView, StoreList, StoreDetail, \
    StoreTransferBook, StoreSaleBook

urlpatterns = [
    # Book
    path('', BookList.as_view(), name="BookList"),
    path('<uuid:id>', BookDetail.as_view(), name="BookDetail"),
    path('<uuid:pk>/upload', BookUploadView.as_view(), name="BookUpload"),
    # Author
    path('authors', AuthorList.as_view(), name="AuthorList"),
    path('authors/<uuid:id>', AuthorDetail.as_view(), name="AuthorDetail"),
    path('stores', StoreList.as_view(), name="StoreList"),
    path('stores/<uuid:id>', StoreDetail.as_view(), name="StoreDetail"),
    path('stores/trans', StoreTransferBook.as_view(), name="StoreTransferBook"),
    path('stores/sale', StoreSaleBook.as_view(), name="StoreSaleBook"),
]

bookmanagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Book Management API",
        default_version='v1',
        description="API documentation for Book Management system",
        contact=openapi.Contact(email="youremail@example.com"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # User
    path('v1/users/', include('user.v1.urls')),
    path('v2/users/', include('user.v2.urls', namespace='user_v2')),
    path('v3/users/', include('user.v3.urls')),

    # Book
    path('v1/books/', include('book.urls')),

    path('api/auth/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Swagger UI
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

user/v1/urls.py
from django.urls import path
from .views import list, detail, create, delete
urlpatterns = [
    path('', list, name='UserList'),
    path('<int:user_id>', detail, name='UserDetail'),
    path('create', create, name='UserCreate'),
    path('delete/<int:user_id>', delete, name='UserDelete'),   
]

user/v2/urls.py
from django.urls import path
from .views import UserList, UserCreate, DetailUpdateUser, DeleteUser
app_name = "user_v2"

urlpatterns = [
    path("", UserList.as_view(), name='UserList'),
    path("create", UserCreate.as_view(), name='UserCreate'),
    path('<int:pk>', DetailUpdateUser.as_view(), name='UserDetail'),
    path('delete/<int:pk>', DeleteUser.as_view(), name='UserDelete'),   
]

user/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    email = models.EmailField(unique=True)
    avatar = models.ImageField(null=True, upload_to='avatars/')

    def __str__(self):
        return self.username

class UploadedFile(models.Model):
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

user/v1/views.py
from ..models import User
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect

def list(request):
    print("List users")
    users = User.objects.all()
    template = loader.get_template("user/list.html")
    context = {
        'users_list': users,
    }
    print(context)
    return HttpResponse(template.render(context, request)) 

def detail(request, user_id):
    user = User.objects.filter(id=user_id).first()
    template = loader.get_template("user/detail.html")
    context = {
        'user': user,
    }
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        valid_email = User.objects.filter(email=email).exclude(id=user_id).first()
        if valid_email:
            context['user'] = None
            context['error'] = "Email already exists"
            return HttpResponse(template.render(context, request))

        user.username = username
        user.email = email
        user.first_name = first_name
        user.last_name = last_name
        user.save(update_fields=['email', 'first_name', 'last_name'])
        return redirect('UserList')
    elif request.method == "GET":
        return HttpResponse(template.render(context, request))

def create(request):
    print(request.POST)
    template = loader.get_template("user/create.html")

    if request.POST:
        username = request.POST.get('username')
        email = request.POST.get('email')

        valid_username = User.objects.filter(username=username).first()
        valid_email = User.objects.filter(email=email).first()

        if valid_username:
            context = {
                'error': "Username already exists"
            }
            return HttpResponse(template.render(context, request))
        if valid_email:
            context = {
                'error': "Email already exists"
            }
            return HttpResponse(template.render(context, request))

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        user = User(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
        )
        user.save()
        return redirect('UserList')
    else:
        context = {}
        return HttpResponse(template.render(context, request))
    
def delete(request, user_id):
    user = User.objects.filter(id=user_id).first()
    template = loader.get_template("user/delete.html")
    if request.method == "POST":
        user.delete()   
        return redirect('UserList')
    elif request.method == "GET":
        context = {
            'user': user,
        }
        return HttpResponse(template.render(context, request))

user/v2/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import User
from django.urls import reverse_lazy

class UserList(ListView):
    model = User
    template_name = "user/list.html"
    context_object_name = "users_list"
    queryset = User.objects.all()

class UserCreate(CreateView):
    model = User
    fields = "__all__"
    template_name = "user/create.html"
    success_url = reverse_lazy("user_v2:UserList")

class DetailUpdateUser(UpdateView):
    model = User
    fields = ['email', 'first_name', 'last_name']
    template_name = "user/detail.html"
    def get_success_url(self):
        return reverse_lazy("user_v2:UserDetail", kwargs = {"pk": self.object.pk})
    
class DeleteUser(DeleteView):
    model = User
    template_name = "user/delete.html"
    def get_success_url(self):
        return reverse_lazy("user_v2:UserList")

user/v3/views.py
from django.contrib.auth import authenticate, login
from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework import status, generics
from rest_framework.views import APIView

from .authentication import CustomTokenObtainPairSerializer
from ..models import User, UploadedFile
from .serializers import UserCreateSerializer, UserRegisterSerializer, UserLoginSerializer, UserListSerializer, \
    UserDetailSerializer, UserUpdateSerializer, UploadedFileSerializer, UploadAvatarSerializer


@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated, IsAdminUser])
def user_list(request):
    if request.method == 'GET':
        user = User.objects.all()
        serializer = UserListSerializer(user, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = UserCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['GET', 'PUT', 'DELETE'])
@permission_classes([IsAuthenticated])
def user_detail(request, pk):
    user = User.objects.filter(pk=pk).first()
    if user is None:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = UserDetailSerializer(user)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = UserUpdateSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    else:
        return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['POST'])
def register_user(request):
    serializer = UserRegisterSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['POST'])
def login_user(request):
    serializer = UserLoginSerializer(data=request.data)
    if serializer.is_valid():
        user = authenticate(
            request,
            username=serializer.validated_data['username'],
            password=serializer.validated_data['password']
        )
        if user:
            login(request, user)
            refresh = CustomTokenObtainPairSerializer.get_token(user)
            data = {
                'refresh': str(refresh),
                'access': str(refresh.access_token)
            }
            return Response(data, status=status.HTTP_200_OK)
        else:
            return Response(
                {"detail": "Username or password is incorrect"},
                status=status.HTTP_401_UNAUTHORIZED
            )
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Upload Image
class FileUploadView(generics.CreateAPIView):
    parser_classes = (MultiPartParser, FormParser,)  # For web forms
    serializer_class = UploadedFileSerializer
    queryset = UploadedFile.objects.all()

    def perform_create(self, serializer):
        serializer.save(file=self.request.data.get('file'))

class AvatarUploadView(generics.UpdateAPIView):
    permission_classes([IsAuthenticated])
    serializer_class = UploadedFileSerializer
    parser_classes = (MultiPartParser, FormParser,)
    serializer_class = UploadAvatarSerializer
    queryset = User.objects.all()
    lookup_field = 'pk'

    def perform_update(self, serializer):
        serializer.save(file=self.request.data.get('file'))

user/templates/user/create.html
{% if error %}
    <div>{{ error }}</div>
{% else %}
    <form action="{% url "user_v2:UserCreate" %}" method="post">
        <h1>Create User</h1>
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username"></input>
        <br>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email"></input>
        <br>
        <label for="firstname">Firstname:</label>
        <input type="text" id="firstname" name="first_name"></input>
        <br>
        <label for="lastname">Lastname:</label>
        <input type="text" id="lastname" name="last_name"></input>
        <br>
        <button type="submit">Create User</button>
    </form>
{% endif %}

user/templates/user/delete.html
<h1>Do you want delete this user</h1>
<form action="" method="post">
    <div>Username: {{ user.username }}</div>
    <div>Email: {{ user.email }}</div>
    <div>Firstname: {{ user.first_name }}</div>
    <div>Lastname: {{ user.last_name }}</div>
    <br>
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
<button><a href="{% url 'user_v2:UserList' %}">Cancel</a></button>

user/templates/user/detail.html
{% if user %}
    <form method="post">
        <h1>Update User</h1>
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username"></input>
        <br>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email"></input>
        <br>
        <label for="firstname">Firstname:</label>
        <input type="text" id="firstname" name="first_name"></input>
        <br>
        <label for="lastname">Lastname:</label>
        <input type="text" id="lastname" name="last_name"></input>
        <br>
        <button type="submit">Update User</button>
        <button><a href="{% url 'UserDelete' user.id %}">Delete</a></button>
        <button><a href="{% url 'UserList'%}">Back to list</a></button>     
    </form>

    <Script>
        window.onload = function() {
            document.getElementById("username").setAttribute("value", "{{ user.username }}");
            document.getElementById("email").setAttribute("value", "{{ user.email }}");
            document.getElementById("firstname").setAttribute("value", "{{ user.first_name }}");
            document.getElementById("lastname").setAttribute("value", "{{ user.last_name }}");
        }
    </Script>
    
{% else %}
    {% if error %}
        <div>{{ error }}</div>
    {% else %}
        <div>User not found</div>
    {% endif %}
{% endif %}

user/templates/user/list.html
<ul>
    <button><a href="{% url 'user_v2:UserCreate' %}">Create</a></button>
    {% for user in users_list %}
        <li>{{ user.username }} - {{ user.email }}</li>
        <button><a href="{% url 'user_v2:UserDetail' user.id %}">View Details</a></button>
        <button><a href="{% url 'user_v2:UserDelete' user.id %}">Delete</a></button>
    {% endfor %}
</ul>